[starcom]
type=peer
host=173.193.144.207
context=starcom-in
insecure=port
disallow=all
allow=ulaw
qualify=yes
dtmfmode=rfc2833
sendrpid=yes

[general]
nat=force_rport,comedia
directmedia=no
context=public
allowoverlap=no
udpbindaddr=0.0.0.0
tcpenable=yes
tcpbindaddr=0.0.0.0
transport=udp
srvlookup=yes
disallow=all
allow=ulaw

; Supervisor WebPhone for Call Monitoring
[supervisor]
type=friend
secret=monitor123
host=dynamic
context=ava-context
disallow=all
allow=ulaw
allow=alaw
nat=force_rport,comedia
directmedia=no
qualify=yes
transport=udp,ws,wss
encryption=no
avpf=yes
force_avp=yes
icesupport=yes
dtmfmode=rfc2833